name: GitHub Actions

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependecies
      run: npm install
    - name: run test-security
      run: npm run test-security

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependecies
      run: npm install
    - name: run test
      run: npm test
