name: GitHub Actions - Build, Test and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 
jobs:
  security_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout of the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependecies
      run: npm install
    - name: run test-security
      run: npm run test-security

  integration_test:
    runs-on: ubuntu-latest
    needs: security_test
    steps:
    - name: Checkout of the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: install dependecies
      run: npm install
    - name: run test
      run: npm test

  deploy_on_render:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: integration_test
    steps:
     - name: Deploy to production
       uses: johnbeynon/render-deploy-action@v0.0.8
       with:
         service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
         api-key: ${{ secrets.MY_RENDER_API_KEY }}

